### ISSUE TITLE
Combinators with short-names (like "rec") get imported automatically

### ISSUE THREAD

**Issue by jonsterling** [agda/cubical#415] opened 2020-09-11 20:02 UTC
When I open a module, like `Cubical.Data.Foo`, I would like the base stuff to come into scope, but the little combinators (like `rec` or `elim`) should surely not be in scope, but instead accessible through some conveniently named module like `Foo.Properties` or something. This is because I will have many different `open import Cubical.Data.Bar` etc., and I don't want a zillion `rec` in scope. One way to resolve this problem is change the convention for the `Properties` module as follows:

```
module Cubical.Data.Foo.Properties where

  module Foo.Properties where
     ...
```

I am not sure my proposal is the most elegant option, so I would like to hear from more experienced Agda users what is preferred here. It seems like the current behavior is not desirable though, unless I am missing some aspect of the intended code-style of client libraries. What do you think?

**Comment by Saizan** [comment] 2020-09-15 12:52
A simple way around this is to `open import Cubical.Data.Foo as Foo` and then use `Foo.rec` and `Bar.rec` and so on.

**Comment by mortberg** [comment] 2020-09-15 13:50
> A simple way around this is to `open import Cubical.Data.Foo as Foo` and then use `Foo.rec` and `Bar.rec` and so on.

Yeah, I think this was the intended way to use these short names that are the same for all HITs. Maybe this should be documented in the CONTRIBUTING file?

**Comment by jonsterling** [comment] 2020-09-15 13:59
I see! If that's the intended style, then we can close this ticket. It might be nice to document it in the `CONTRIBUTING` file though.

Thank you!

**Comment by ecavallo** [comment] 2020-09-15 14:12
There is still one rough spot in the way things work right now. `open import Cubical.Data.Foo as Foo` is nice because you can use unambiguous names in `Cubical.Data.Foo` without qualification, only qualifying `rec` and `elim` and such that need it. The problem is when you want to _define_ a `rec` or `elim` in your own module; then you're told off for shadowing the ones in `Cubical.Data.Foo`. Thus we end up with `hiding (rec; elim)`'s in `Cubical.HITs.Truncation.Properties` for example.

It doesn't come up that often, so maybe it's okay.

**Comment by Saizan** [comment] 2020-09-16 08:00
I wonder if we can petition for that shadowing error to be turned into a warning, or have a pragma to say that it's ok.

**Comment by jonsterling** [comment] 2020-09-20 02:21
Personally I don't feel that systematically shadowing stuff is a good way to design a library, but I agree that shadowing should be a warning and not an error (as a separate matter, for semantic reasons).

Evan makes a good point. Anyway, I feel that the current style of the library forces us to do a lot of `hiding` and `using` this and that in ordinary/non-exceptional scenarios, and it would be great to find something that worked better in these everyday scenarios. I do not think my suggestion at the top was a good one, though.

With all this said, I think you should feel very free to close this ticket if it is sapping the team's ch'i... Believe me, I understand 😆

**Comment by Saizan** [comment] 2020-09-21 08:33
I'm more worried about local shadowing than across-modules shadowing. Btw, some advocate to always have a `using` clause when `open`ing a module. So the policies are indeed quite varied.

I do prefer `Foo.rec` rather than `recFoo` and we want to keep the `Foo` part not too verbose.

That said it could be `FooM` where the `M` is for module. It has to be a unique name otherwise the same problem applies.

By the way, for every datatype one gets a module of the same name with the constructors in it. An option would be to "add" to that module in the `*.Properties` file:

`Cubical.Data.Foo.Properties`:
```agda
open import Cubical.Data.Foo.Base renaming (module Foo to BareFoo)

module Foo where
  open BareFoo public
  rec : ...
  elim : ...
```

then in `Cubical.Data.Foo` we have
```agda
open import Cubical.Data.Foo.Base hiding (module Foo)
open import Cubical.Data.Foo.Properties
```

and in a file with `open import Cubical.Data.Foo` you would have `Foo.rec` available.

**Comment by mortberg** [comment] 2020-10-13 18:44
Closing this now. Feel free to reopen if someone wants to discuss this more

**Closed by mortberg** 2020-10-13 18:44 UTC
