### ISSUE TITLE
Cubical not typechecking upon install

### ISSUE THREAD

**Issue by cosmoviola** [agda/cubical#932] opened 2022-09-13 21:28 UTC
I am trying to install the Cubical library for agda. I already had an existing agda installation, but I followed the directions [here](https://github.com/agda/cubical/blob/master/INSTALL.md) and set Cabal to overwrite the existing installation using the --overwrite-policy=always flag. This seemed to work, but when I run make to typecheck the cubical files, as suggested in the installation instructions, I get the following error: [cubical_build_error.txt](https://github.com/agda/cubical/files/9560894/cubical_build_error.txt). The last file to fail to typecheck is Cubical/Data/FinData/Properties.agda with unsolved metavariables.

Did I make a mistake when installing the library? I would appreciate suggestions as to how to fix this.

**Comment by cosmoviola** [comment] 2022-09-13 21:31
Adding @tlringer because we are working together on a project.

**Comment by felixwellen** [comment] 2022-09-13 21:34
I looks like you are using a version of agda newer than 2.6.2.2 (this is the version we use to check the library) - can you check that with ```agda --version```?

**Comment by plt-amy** [comment] 2022-09-13 21:36
This is a known regression on Agda's master branch relative to 2.6.2.2 (https://github.com/agda/agda/issues/6074). The cubical library does not track Agda's master branch.

**Comment by tlringer** [comment] 2022-09-13 21:37
Oh, thank you! Is this documented anywhere? The installation instructions we followed didn't mention that the cubical library tracks on a different version of Agda.

**Comment by tlringer** [comment] 2022-09-13 21:43
In particular, I'd like to suggest in the meantime that if this tracks on specific installations of Agda, that specific installation is documented [here](https://github.com/agda/cubical/blob/master/INSTALL.md) for new users, or otherwise the instructions provided default to that specific installation (latter is probably better since then you don't need to modify the INSTALL.md every time).

**Comment by felixwellen** [comment] 2022-09-14 06:48
Here is a draft, comments welcome:

[https://github.com/agda/cubical/blob/install_latest_release/INSTALL.md](https://github.com/agda/cubical/blob/install_latest_release/INSTALL.md)

I added how to checkout the tag for the latest release, for cabal-v2, cabal sandbox and stack-instructions. I only use stack myself, but I cannot imagine how that step could be different with other build tools. I also made the "latest release of agda" in the beginning of the page more visible by turning it into a link to a page that tells you which agda version is the latest release.

**Comment by felixwellen** [comment] 2022-09-14 06:56
Now it is also a draft PR: [https://github.com/agda/cubical/pull/933](https://github.com/agda/cubical/pull/933)

**Comment by mortberg** [comment] 2022-09-14 07:08
Not about this PR, but @cosmoviola  and @tlringer  are very welcome to join our Univalent Agda Discord server: https://discord.gg/yjTKHzepMx

There is a channel for this library there and you're very welcome to join and ask any questions you might have about the library or installation issues!

**Comment by felixwellen** [comment] 2022-09-14 09:07
I am happy with PR #933 now - @cosmoviola , @tlringer please have a look and let me know if you think the problem is resolved. Thanks for reporting!
Everyone with rights to do so: feel free to improve the PR without asking - I put it on this repo, so you can just push to it.

**Comment by tlringer** [comment] 2022-09-14 14:21
LGTM. @cosmoviola , did you manage to get this working with the updated instructions?

**Comment by cosmoviola** [comment] 2022-09-14 22:16
I just ran it, the updated instructions fix the problem. Looks good to me.

**Comment by felixwellen** [comment] 2022-09-15 08:07
Ok, good - I'll merge that then.

**Comment by felixwellen** [comment] 2022-09-15 08:10
Done, closing issue since it is resolved.

**Closed by felixwellen** 2022-09-15 08:10 UTC
