### ISSUE TITLE
Error 42: UnsupportedYet Injectivity

### ISSUE THREAD

**Issue by djspacewhale** [agda/cubical#626] opened 2021-11-18 20:45 UTC
On the current beta for Windows 11 (in Ubuntu WSL2), with the current Agda development library, running cubical/make throws this error:

```
`/home/dj/cubical/Cubical/Data/FinData/Base.agda:37,1-40,24

Could not generate equivalence when splitting on indexed family,

the function will not compute on transports by a path.

  Reason: UnsupportedYet Injectivity

                           position:    0

                           type:        ℕ

                           datatype:    ℕ

                           parameters:

                           indices:

                           constructor: suc

when checking the definition of _==_

make: *** [GNUmakefile:47: check] Error 42`
```

**Comment by Saizan** [comment] 2021-11-19 11:04
@djspacewhale can you confirm the problem is fixed now?

**Comment by Saizan** [comment] 2021-11-20 10:53
`make` should go through cleanly on agda/master now.

**Closed** 2021-11-22 16:04 UTC
